### ISSUE TITLE
xHub To-Do list

### ISSUE THREAD

**Issue by xFaceLess** [xFaceLess/xHub#1]
#Features:

- [ ] Disable/enable and customize join/leave messages
- [ ] Double jump attribute
- [ ] Keep/full food level in certain areas such as the spawn, or everywhere
- [ ] Keep/full health level in certain areas such as the spawn, or everywhere
- [ ] Extensive BungeeCord support
- [ ] Launch pads with proper settings
- [ ] Basic information signs
- [ ] Fixed weather
- [ ] Extensive MOTD settings (Alternating, color codes)
- [ ] Returning from VoidFall 
- [ ] Override and customize messages for any given command, such as /plugin with bypass permission
- [ ] Predefined set of items your inventory must contain on connect
- [ ] Automated broadcast system using the chat and boss bar
- [ ] Per world configuration for settings where this is useful
- [ ] Add support for changing all of the messages
- [ ] Custom text holograms
- [ ] Friends System
- [ ] Visibilaty System
- [ ] Warp System
- [ ] NameTagEdit System´

#Maybe:

_need to think in these first_

- [ ] Custom Health
- [ ] Custom Hunger
- [ ] Custom Armor
- [ ] Custom Respiration
